title: To The Beginning of Awesomeness
author: Soumik Barua
email: 1155165834@link.cuhk.edu.hk.com
description: > # this means to ignore newlines until "baseurl:"
  Meaning is a Jumper that you have to knit yourself

# social links
instageam_username: soumik_b_ # DO NOT include the @ character, or else the build will fail!
github_username:  Soumik-b # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
